#!/usr/bin/env python
#.git/hooks/post-commit

#Imports
## Use this to get the github commit message
from subprocess import check_output
## A user-friendly twitter api lib
import tweepy
## Going to read in my sensitive twitter credentials with configparser
import configparser
import os

#Variables
## Call out to check_output to get the last commit info
commitMsg = check_output(["git", "log", "-1"])
## my .ini formatted twitter data.  This needs to be relative to the root of your github project because the hooks won't traverse your whole file system.
myPrecious = "private/twitter-api.properties"

## Read in the twitter info from my private path (gitignored)
config = configparser.ConfigParser()
if os.path.isfile(myPrecious):
    print('Loading sensitive data from ' + myPrecious)
    config.read(myPrecious)
else:
    print('Couldn\'t find your properties file at ' + myPrecious)

consumerKey=config.get('Consumer','ConsumerKey')
consumerSecret=config.get('Consumer','ConsumerSecret')
accessToken=config.get('Access','AccessToken')
accessTokenSecret=config.get('Access','AccessTokenSecret')
auth = tweepy.OAuthHandler(consumerKey, consumerSecret)
auth.set_access_token(accessToken, accessTokenSecret)

# Main 
## Now we'll use tweepy to push my commit message
api = tweepy.API(auth)
api.update_status(commitMsg)
